apiVersion: v1
kind: Namespace
metadata:
  name: runnable-run
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-mock-server-deployment
  namespace: runnable-run
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: demo-mock-server
  template:
    metadata:
      labels:
        app: demo-mock-server
    spec:
      containers:
        - name: demo-mock-server
          image: registry.cn-hongkong.aliyuncs.com/runnable-run/demo-mock-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: NINJA_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ninja-api-secret
                  key: token
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: host
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: port
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: db
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: demo-mock-server-service
  namespace: runnable-run
spec:
  selector:
    app: demo-mock-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-mock-server-ingress
  namespace: runnable-run
spec:
  rules:
    - host: numfeel-api.996.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-mock-server-service
                port:
                  number: 80
    - host: bit0.numfeel.996.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-mock-server-service
                port:
                  number: 80
    - host: bit1.numfeel.996.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-mock-server-service
                port:
                  number: 80
    - host: bit2.numfeel.996.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-mock-server-service
                port:
                  number: 80
    - host: bit3.numfeel.996.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-mock-server-service
                port:
                  number: 80
    - host: bit4.numfeel.996.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-mock-server-service
                port:
                  number: 80
    - host: bit5.numfeel.996.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-mock-server-service
                port:
                  number: 80
    - host: bit6.numfeel.996.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-mock-server-service
                port:
                  number: 80
    - host: bit7.numfeel.996.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-mock-server-service
                port:
                  number: 80
    - host: bit8.numfeel.996.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-mock-server-service
                port:
                  number: 80
    - host: bit9.numfeel.996.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-mock-server-service
                port:
                  number: 80
    - host: bit10.numfeel.996.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-mock-server-service
                port:
                  number: 80
    - host: bit11.numfeel.996.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-mock-server-service
                port:
                  number: 80
    - host: bit12.numfeel.996.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-mock-server-service
                port:
                  number: 80
    - host: bit13.numfeel.996.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-mock-server-service
                port:
                  number: 80
    - host: bit14.numfeel.996.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-mock-server-service
                port:
                  number: 80
    - host: bit15.numfeel.996.ninja
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-mock-server-service
                port:
                  number: 80
