/**
 * HTML vs Markdown 对比场景数据
 * 每个场景包含同一份原始数据的 Markdown 和 HTML 表达
 */
var SCENARIOS = [
  {
    id: 'api-doc',
    title: 'API 接口文档',
    desc: '一个 REST API 端点的完整描述',
    source: '模拟数据：基于常见 REST API 文档结构',
    markdown: [
      '## POST /api/users',
      '',
      '创建新用户。',
      '',
      '### 请求参数',
      '',
      '| 字段 | 类型 | 必填 | 说明 |',
      '|------|------|------|------|',
      '| name | string | 是 | 用户名，2-20字符 |',
      '| email | string | 是 | 邮箱地址 |',
      '| role | enum | 否 | admin / editor / viewer |',
      '| avatar | string | 否 | 头像URL |',
      '',
      '### 响应状态码',
      '',
      '- `201` 创建成功',
      '- `400` 参数校验失败',
      '- `409` 邮箱已存在',
      '',
      '### 示例请求',
      '',
      '```json',
      '{',
      '  "name": "张三",',
      '  "email": "zhang@example.com",',
      '  "role": "editor"',
      '}',
      '```'
    ].join('\n'),
    html: '<div class="api-doc"><div class="api-method"><span class="method-badge post">POST</span><code>/api/users</code><span class="api-tag">需要认证</span></div><p class="api-desc">创建新用户。</p><h4>请求参数</h4><table class="param-table"><thead><tr><th>字段</th><th>类型</th><th>必填</th><th>说明</th></tr></thead><tbody><tr><td><code>name</code></td><td><span class="type-badge">string</span></td><td><span class="required">必填</span></td><td>用户名，2-20字符</td></tr><tr><td><code>email</code></td><td><span class="type-badge">string</span></td><td><span class="required">必填</span></td><td>邮箱地址</td></tr><tr><td><code>role</code></td><td><span class="type-badge">enum</span></td><td><span class="optional">可选</span></td><td><code>admin</code> <code>editor</code> <code>viewer</code></td></tr><tr><td><code>avatar</code></td><td><span class="type-badge">string</span></td><td><span class="optional">可选</span></td><td>头像URL</td></tr></tbody></table><h4>响应状态码</h4><div class="status-list"><div class="status-item"><span class="status-code s2xx">201</span>创建成功</div><div class="status-item"><span class="status-code s4xx">400</span>参数校验失败</div><div class="status-item"><span class="status-code s4xx">409</span>邮箱已存在</div></div><h4>示例请求</h4><pre class="code-block"><code>{\n  "name": "张三",\n  "email": "zhang@example.com",\n  "role": "editor"\n}</code></pre></div>',
    metrics: {
      markdownChars: 380,
      htmlChars: 1120,
      markdownInfoItems: 12,
      htmlInfoItems: 18,
      htmlExtraFeatures: ['颜色编码状态码', '类型徽章', '必填/可选标识', '方法类型颜色']
    }
  },
  {
    id: 'meeting-notes',
    title: '会议纪要',
    desc: '一次产品评审会的记录',
    source: '模拟数据：基于常见产品评审会议结构',
    markdown: [
      '## 产品评审会 — 2026-05-20',
      '',
      '**参会人：** 张明（产品）、李薇（设计）、王磊（后端）、赵雪（前端）',
      '',
      '### 议题一：首页改版',
      '',
      '- 状态：进行中',
      '- 结论：保留左侧导航，右侧内容区宽度从 960px 改为自适应',
      '- 负责人：李薇',
      '- 截止日期：5月27日',
      '',
      '### 议题二：性能优化',
      '',
      '- 状态：待开始',
      '- 结论：首屏加载目标 < 2s，先优化图片懒加载',
      '- 负责人：赵雪',
      '- 截止日期：6月3日',
      '',
      '### 议题三：API 限流方案',
      '',
      '- 状态：已完成',
      '- 结论：采用令牌桶算法，每用户100次/分钟',
      '- 负责人：王磊',
      '',
      '### 待办',
      '',
      '- [ ] 李薇出首页高保真图',
      '- [ ] 赵雪做性能基准测试',
      '- [ ] 王磊更新限流文档'
    ].join('\n'),
    html: '<div class="meeting-doc"><div class="meeting-header"><h3>产品评审会</h3><div class="meeting-meta"><span class="meta-item"><i class="ti ti-calendar"></i> 2026-05-20</span><span class="meta-item"><i class="ti ti-users"></i> 4人参会</span></div><div class="attendees"><span class="attendee pm">张明 · 产品</span><span class="attendee design">李薇 · 设计</span><span class="attendee be">王磊 · 后端</span><span class="attendee fe">赵雪 · 前端</span></div></div><div class="agenda-list"><div class="agenda-item"><div class="agenda-head"><span class="agenda-status in-progress">进行中</span><strong>首页改版</strong><span class="agenda-owner">李薇</span><span class="agenda-deadline">截止 5/27</span></div><p>保留左侧导航，右侧内容区宽度从 960px 改为自适应</p></div><div class="agenda-item"><div class="agenda-head"><span class="agenda-status todo">待开始</span><strong>性能优化</strong><span class="agenda-owner">赵雪</span><span class="agenda-deadline">截止 6/3</span></div><p>首屏加载目标 &lt; 2s，先优化图片懒加载</p></div><div class="agenda-item"><div class="agenda-head"><span class="agenda-status done">已完成</span><strong>API 限流方案</strong><span class="agenda-owner">王磊</span></div><p>采用令牌桶算法，每用户100次/分钟</p></div></div><div class="todo-section"><h4><i class="ti ti-checkbox"></i> 待办事项</h4><label class="todo-item"><input type="checkbox"><span>李薇出首页高保真图</span></label><label class="todo-item"><input type="checkbox"><span>赵雪做性能基准测试</span></label><label class="todo-item"><input type="checkbox"><span>王磊更新限流文档</span></label></div></div>',
    metrics: {
      markdownChars: 326,
      htmlChars: 1480,
      markdownInfoItems: 14,
      htmlInfoItems: 22,
      htmlExtraFeatures: ['状态颜色标签', '角色颜色编码', '可交互复选框', '图标辅助信息', '时间线结构']
    }
  },
  {
    id: 'color-palette',
    title: '设计规范 — 色板',
    desc: '品牌色彩系统文档',
    source: '模拟数据：基于 Material Design 色彩规范结构',
    markdown: [
      '## 品牌色板',
      '',
      '### 主色',
      '',
      '- Primary: `#6366F1` (Indigo 500)',
      '- Primary Light: `#A5B4FC` (Indigo 300)',
      '- Primary Dark: `#4338CA` (Indigo 700)',
      '',
      '### 语义色',
      '',
      '- Success: `#10B981`',
      '- Warning: `#F59E0B`',
      '- Error: `#EF4444`',
      '- Info: `#3B82F6`',
      '',
      '### 中性色',
      '',
      '- Gray 50: `#F9FAFB`',
      '- Gray 100: `#F3F4F6`',
      '- Gray 500: `#6B7280`',
      '- Gray 900: `#111827`',
      '',
      '### 使用规则',
      '',
      '- 主色用于CTA按钮和关键链接',
      '- 语义色仅用于状态反馈',
      '- 正文使用 Gray 900，辅助文字使用 Gray 500'
    ].join('\n'),
    html: '<div class="color-doc"><h3>品牌色板</h3><div class="color-section"><h4>主色</h4><div class="color-grid"><div class="color-swatch" style="background:#6366F1"><span class="swatch-name">Primary</span><span class="swatch-hex">#6366F1</span><span class="swatch-ref">Indigo 500</span></div><div class="color-swatch" style="background:#A5B4FC"><span class="swatch-name" style="color:#333">Primary Light</span><span class="swatch-hex" style="color:#333">#A5B4FC</span><span class="swatch-ref" style="color:#555">Indigo 300</span></div><div class="color-swatch" style="background:#4338CA"><span class="swatch-name">Primary Dark</span><span class="swatch-hex">#4338CA</span><span class="swatch-ref">Indigo 700</span></div></div></div><div class="color-section"><h4>语义色</h4><div class="color-grid semantic"><div class="color-swatch" style="background:#10B981"><span class="swatch-name">Success</span><span class="swatch-hex">#10B981</span></div><div class="color-swatch" style="background:#F59E0B"><span class="swatch-name" style="color:#333">Warning</span><span class="swatch-hex" style="color:#333">#F59E0B</span></div><div class="color-swatch" style="background:#EF4444"><span class="swatch-name">Error</span><span class="swatch-hex">#EF4444</span></div><div class="color-swatch" style="background:#3B82F6"><span class="swatch-name">Info</span><span class="swatch-hex">#3B82F6</span></div></div></div><div class="color-section"><h4>中性色</h4><div class="color-strip"><div class="strip-item" style="background:#F9FAFB"><span style="color:#333">50</span></div><div class="strip-item" style="background:#F3F4F6"><span style="color:#333">100</span></div><div class="strip-item" style="background:#6B7280"><span>500</span></div><div class="strip-item" style="background:#111827"><span>900</span></div></div></div><div class="color-rules"><h4>使用规则</h4><div class="rule-item"><span class="rule-swatch" style="background:#6366F1"></span>主色用于CTA按钮和关键链接</div><div class="rule-item"><span class="rule-swatch" style="background:linear-gradient(90deg,#10B981,#F59E0B,#EF4444,#3B82F6)"></span>语义色仅用于状态反馈</div><div class="rule-item"><span class="rule-swatch" style="background:#111827"></span>正文 Gray 900 <span class="rule-swatch" style="background:#6B7280;margin-left:8px"></span>辅助 Gray 500</div></div></div>',
    metrics: {
      markdownChars: 388,
      htmlChars: 1820,
      markdownInfoItems: 13,
      htmlInfoItems: 13,
      htmlExtraFeatures: ['实际色块展示', '渐变色条', '所见即所得', '无需脑内渲染 hex 码']
    }
  },
  {
    id: 'changelog',
    title: '版本更新日志',
    desc: '软件版本发布记录',
    source: '模拟数据：基于 Keep a Changelog 规范',
    markdown: [
      '## v2.4.0 (2026-05-18)',
      '',
      '### 新增',
      '',
      '- 支持暗色模式',
      '- 新增批量导出功能',
      '- WebSocket 实时通知',
      '',
      '### 修复',
      '',
      '- 修复分页组件在 Safari 下的布局错位',
      '- 修复文件上传偶发的超时问题',
      '',
      '### 变更',
      '',
      '- 最低 Node.js 版本要求从 16 升至 18',
      '- 弃用 /api/v1/legacy 端点（将在 3.0 移除）',
      '',
      '---',
      '',
      '## v2.3.2 (2026-05-02)',
      '',
      '### 修复',
      '',
      '- 修复登录页面在移动端的键盘遮挡问题',
      '- 修复 CSV 导出中文乱码'
    ].join('\n'),
    html: '<div class="changelog-doc"><div class="version-block"><div class="version-header"><span class="version-tag">v2.4.0</span><span class="version-date">2026-05-18</span><span class="version-label major">功能更新</span></div><div class="change-group"><div class="change-category added"><span class="cat-icon">✦</span><span class="cat-label">新增</span></div><ul><li>支持暗色模式</li><li>新增批量导出功能</li><li>WebSocket 实时通知</li></ul></div><div class="change-group"><div class="change-category fixed"><span class="cat-icon">⚡</span><span class="cat-label">修复</span></div><ul><li>分页组件在 Safari 下的布局错位</li><li>文件上传偶发的超时问题</li></ul></div><div class="change-group"><div class="change-category changed"><span class="cat-icon">⚠</span><span class="cat-label">变更</span></div><ul><li>最低 Node.js 版本要求 <span class="version-bump">16 → 18</span></li><li>弃用 <code>/api/v1/legacy</code> <span class="deprecated-badge">将在 3.0 移除</span></li></ul></div></div><div class="version-block old"><div class="version-header"><span class="version-tag">v2.3.2</span><span class="version-date">2026-05-02</span><span class="version-label patch">补丁</span></div><div class="change-group"><div class="change-category fixed"><span class="cat-icon">⚡</span><span class="cat-label">修复</span></div><ul><li>登录页面在移动端的键盘遮挡问题</li><li>CSV 导出中文乱码</li></ul></div></div></div>',
    metrics: {
      markdownChars: 262,
      htmlChars: 1560,
      markdownInfoItems: 10,
      htmlInfoItems: 16,
      htmlExtraFeatures: ['版本类型标签', '变更类型颜色', '版本升级箭头', '弃用警告标识']
    }
  },
  {
    id: 'dashboard-report',
    title: '数据周报',
    desc: '产品关键指标的周度汇报',
    source: '模拟数据：基于常见 SaaS 产品数据周报结构',
    markdown: [
      '## 产品周报 — 第21周（5/12 - 5/18）',
      '',
      '### 核心指标',
      '',
      '- DAU: 12,450（+8.3%）',
      '- 新注册: 1,203（+15.2%）',
      '- 付费转化率: 3.2%（-0.1pp）',
      '- 次日留存: 42.5%（+1.8pp）',
      '- 平均时长: 8.7min（+0.5min）',
      '',
      '### 重点事件',
      '',
      '- 周二推送活动带来 DAU 峰值（14,200）',
      '- 新用户引导流程改版上线',
      '- iOS 端崩溃率升高至 0.8%（已修复）',
      '',
      '### 下周计划',
      '',
      '- A/B 测试新定价页',
      '- 上线 Push 分层策略',
      '- 修复安卓端推送到达率问题'
    ].join('\n'),
    html: '<div class="report-doc"><div class="report-header"><h3>产品周报</h3><span class="report-week">第21周 · 5/12 - 5/18</span></div><div class="metrics-grid"><div class="metric-card up"><div class="metric-value">12,450</div><div class="metric-label">DAU</div><div class="metric-change up">↑ 8.3%</div></div><div class="metric-card up"><div class="metric-value">1,203</div><div class="metric-label">新注册</div><div class="metric-change up">↑ 15.2%</div></div><div class="metric-card down"><div class="metric-value">3.2%</div><div class="metric-label">付费转化</div><div class="metric-change down">↓ 0.1pp</div></div><div class="metric-card up"><div class="metric-value">42.5%</div><div class="metric-label">次日留存</div><div class="metric-change up">↑ 1.8pp</div></div><div class="metric-card up"><div class="metric-value">8.7min</div><div class="metric-label">平均时长</div><div class="metric-change up">↑ 0.5min</div></div></div><div class="report-section"><h4><i class="ti ti-alert-circle"></i> 重点事件</h4><div class="event-timeline"><div class="event good"><span class="event-day">周二</span>推送活动带来 DAU 峰值（14,200）</div><div class="event neutral"><span class="event-day">周三</span>新用户引导流程改版上线</div><div class="event bad"><span class="event-day">周四</span>iOS 崩溃率升高至 0.8%<span class="event-tag resolved">已修复</span></div></div></div><div class="report-section"><h4><i class="ti ti-calendar-event"></i> 下周计划</h4><div class="plan-list"><div class="plan-item">A/B 测试新定价页</div><div class="plan-item">上线 Push 分层策略</div><div class="plan-item">修复安卓端推送到达率问题</div></div></div></div>',
    metrics: {
      markdownChars: 277,
      htmlChars: 1680,
      markdownInfoItems: 14,
      htmlInfoItems: 22,
      htmlExtraFeatures: ['涨跌颜色编码', '指标卡片布局', '事件时间线', '状态标签（已修复）']
    }
  }
];
